### PR TITLE
Add LLILC project page

### PR DESCRIPTION
**Pull request by martinwoodward**
Creating a new project page for LLILC

### CODE REVIEW

**Comment by russellhadley** [comment]
@stephentoub makes a good point.  The intent of the sentences was to say the LLILC *project* has the goal but the way it reads now makes it seem like the compiler itself has the goal.  Maybe this: "LLILC is an LLVM based MSIL Compiler - we pronounce it 'lilac'.  The goal of the project is build a set of cross-platform .NET code generation tools that utilize LLVM to reach a broad set of platforms and targets."

**Comment by russellhadley** [comment]
If we can work up a good wording here I'll take it and make the same change to the LLILC readme.md.

**Comment by martinwoodward** [comment]
How about now

LLILC (pronounced 'lilac') is an **LL**VM based MS**IL C**ompiler. The goal of the project is to produce a set of .NET tools that utilize LLVM to reach a broad set of platforms and chip architectures. Today LLILC is being developed against [dotnet/CoreCLR](https://github.com/dotnet/coreclr) for use as a JIT, but an ahead of time (AOT) compiler is planned for the future.

**Comment by russellhadley** [comment]
Looks good.  You did drop the 'code generation' from between ".NET" and "tools".  Do you think that helps simplify things and is implied by LLVM?  In my read I thought to add it but realized you'd just removed it. To my thinking "tools" is kind of broad, would ".NET code generators" be better than ".NET tools"?

**Pull request merged**
