### PR TITLE
Added Nancy to README.md

### PR DESCRIPTION
**Pull request by thecodejunkie**

### CODE REVIEW

**Comment by martinwoodward** [comment]
❤️ Welcome! ❤️ - would it be possible to also add a file into the projects directory as well so that you show up in the project directory on the website?  Take a look at #63 or #59 for some examples.

**Comment by thecodejunkie** [comment]
@martinwoodward Thanks! I've added Nancy to the project directory 😄

**Comment by martinwoodward** [comment]
Not sure how well the GitHub -> Orchard stuff handles fancy markdown yet, let's find out!

**Comment by thecodejunkie** [comment]
YOLO!

**Comment by martinwoodward** [comment]
Not awesome is the answer: http://www.dotnetfoundation.org/nancy - however let me go see if I can get the CSS fixed rather than changing your markdown...

**Comment by thecodejunkie** [comment]
If you want you can just remove the code snippet. No biggy

**Comment by martinwoodward** [comment]
We're updating the CSS to support code better but it will be straight MarkDown style rather than GitHub flavoured. I'll update the Project page when it's ready.

**Pull request merged**
